
CREATE TABLE STUDENT (ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(45),
LAST_NAME VARCHAR(45),
GPA FLOAT(10)

 );


INSERT INTO STUDENT (ID, FIRST_NAME, LAST_NAME, GPA) VALUES (2, 'ALI', 'AHMAD',4.0);

